### ISSUE TITLE
Compiling citrus with latest ctrulib (commit 1cef3e5)

### ISSUE THREAD

**Issue by PeggerWed** [Steveice10/citrus#20]
Compiling citrus with latest ctrulib (commit 1cef3e5) gives following errors
(Compiling with previous commit works fine)

```
build/source/citrus/app.o
source/citrus/app.cpp: In function 'void ctr::app::launch(ctr::app::App)':
source/citrus/app.cpp:460:20: error: 'aptOpenSession' was not declared in this s
cope
     aptOpenSession();
                    ^
source/citrus/app.cpp:461:124: error: 'APT_PrepareToDoAppJump' was not declared
in this scope
     ctr::err::parse(ctr::err::SOURCE_APT_PREPARE_TO_DO_APP_JUMP, (u32) APT_Prep
areToDoAppJump(0, app.titleId, app.mediaType));

                                            ^
source/citrus/app.cpp:463:102: error: 'APT_DoAppJump' was not declared in this s
cope
         ctr::err::parse(ctr::err::SOURCE_APT_DO_APP_JUMP, (u32) APT_DoAppJump(0
x300, 0x20, buf0, buf1));

                      ^
source/citrus/app.cpp:466:21: error: 'aptCloseSession' was not declared in this
scope
     aptCloseSession();
                     ^
make: *** [build/source/citrus/app.o] Error 1
rm build/source/citrus/citrus_default_font.bin.c build/source/citrus/citrus_defa
ult_shader.shbin.c
```

**Comment by Steveice10** [comment]
Fixed.

**Comment by d0k3** [comment]
From what I see, not fixed - the libkhax submodule has to be updated, too.

**Comment by Steveice10** [comment]
When the comment was made, libkhax had yet to be fixed.
